### ISSUE TITLE
Need to update mauth-client to include query parameters in mAuth signature

### ISSUE THREAD

**Issue by raroskar-mdsol** [mdsol/mauth-client-dotnet#33]
Background
Medicines and Healthcare products Regulatory Agency (MHRA)'s review of Medidata Products, they observed, ** 
The protocol used to authenticate remote applications, mAuth, was used inconsistently in that important elements of the message were excluded from the signature (specifically the use of function verbs in URL queries), thus functions were not authenticated, which could introduce the risk that functions could be substituted (e.g. overwrite data instead of append to a record). ** 
 
What is expected?

- mauth-client has new mauth request signing algorithm (MWSV2) , which will have authentication header looking similar to original 'x-mws-authentication' header and in addition it will append the query params k-v pairs, sorted ascending by key.
- mauth-client should maintain backwards compatibility i.e. original MWS (current signature algorithm) should still be available and usable. 
- mauth-client must be able to sign with both MWS and MWSV2 for requests. 
- mauth-client should have sufficient logging such that it will be easy to figure out how many (and who) requests are still using MWS vs MWSV2 in any given time period

**Comment by lschreck-mdsol** [comment]
Thank you for opening this issue @raroskar-mdsol - we created a ticket for this in our internal issue tracker and soon we will start to tackle this.

**Comment by danielloganking** [comment]
@raroskar-mdsol @lschreck-mdsol Can this be closed? IIRC this is what MAuthV2 addresses?

**Comment by lschreck-mdsol** [comment]
@danielloganking Yeah this is an old issue and you are right, MWS2 is resolving this one (we are not tracking issues in GitHub that's why this was not closed yet).

Thanks for the heads up, I am closing it now.
